package X;

import java.util.Set;

/* renamed from: X.1AN  reason: invalid class name */
public abstract class AnonymousClass1AN {
    public static final Set A00 = AnonymousClass1AP.A03("libwa_log.so", "libessential.so", "libvlc.so", "libwhatsappp.so", "libcurve25519.so", "libfb.so", "libfbjni.so", "libglog.so", "libc++_shared.so", "libhiddenapis2.so", "libunwindstack_shared.so");
    public static final Set A01 = AnonymousClass1AP.A03("libaom.so", "libwzav1.so", "libopus_mlow.so", "libgifimage.so", "libmagi.so", "libstatic-webp.so", "libohai.so", "liblib_fb_fbjni.so", "libflexlayout.so", "libprofilo.so", "libprofilo_atrace.so", "libprofilo_build.so", "libprofilo_fb.so", "libprofilo_util.so", "libprofilo_sigmux.so", "libprofilo_mmapbuf.so", "libprofilo_fmt.so", "libprofilo_plthooks.so", "libprofilo_linker.so", "libprofilo_systemcounters.so", "libprofilo_stacktrace.so", "libprofilo_threadmetadata.so", "libprofilo_multi_buffer_logger.so", "libprofilo_counters.so", "libprofilo_mmapbuf_buffer.so", "libprofilo_mmapbuf_buffer_jni.so", "libprofilo_jmulti_buffer_logger.so", "libprofilo_logger.so", "libprofiloextapi.so", "libprofilo_stack_unwinder.so", "libprofilo_mapping_logger.so", "libprofilo_local_symbols.so", "libminscompiler-jni.so", "libyoga.so", "libunityjni.so", "libggml_core_ops_universal.so", "libggml_core_ops_enhanced.so", "libsmartglasses-bundle.so", "libarci.so", "libkaleidoscope.so", "libxplat_rsys_foundation_logging_tslog_thrift_tslog_data-cpp2-typesAndroid.so", "libar-bundle1.so", "libar-bundle2.so", "libar-bundle3.so", "libar-bundle4.so", "libar-bundle5.so", "libarcore_sdk_c.so", "libfbjni_kt.so", "libfbsofterror.so", "libgraphicsengine-arengineservices-whatsappservicehost-native.so", "libpytorch.so", "libtorch-code-gen.so", "libexecutorch.so");
    public static final Set A02 = AnonymousClass1AP.A03("libevent.so", "libevent-2.1.so", "libevent_core.so", "libevent_core-2.1.so", "libevent_extra.so", "libevent_extra-2.1.so", "libflexlayout.so", "libflipper.so", "libflipperfb.so");
}
