package X;

/* renamed from: X.203  reason: invalid class name */
public abstract class AnonymousClass203 {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    public static final String A09;
    public static final String A0A;
    public static final String A0B;
    public static final String A0C;
    public static final String A0D;
    public static final String A0E;
    public static final String A0F;
    public static final String A0G;
    public static final String A0H;
    public static final String A0I;
    public static final String A0J;
    public static final String A0K;
    public static final String A0L;
    public static final String A0M;
    public static final String A0N;
    public static final String A0O;
    public static final String A0P;

    static {
        StringBuilder sb = new StringBuilder();
        sb.append("SELECT ");
        String str = C209514c.A00;
        sb.append(str);
        sb.append(" FROM ");
        sb.append("available_message_view");
        sb.append(" WHERE ");
        sb.append("chat_row_id = ?");
        sb.append(" AND ");
        sb.append("from_me = 0");
        sb.append(" AND ");
        sb.append("sort_id <= ?");
        sb.append(" AND ");
        sb.append("sort_id > ?");
        sb.append(" AND ");
        sb.append("status NOT IN (16, 10)");
        sb.append(" AND ");
        sb.append("message_type NOT IN ('8', '10', '15')");
        sb.append(" ORDER BY sort_id DESC ");
        sb.append("LIMIT 4096");
        A0P = sb.toString();
        StringBuilder sb2 = new StringBuilder();
        sb2.append("   SELECT ");
        sb2.append(str);
        sb2.append(" FROM ");
        sb2.append("available_message_view");
        sb2.append(" WHERE ");
        sb2.append("chat_row_id = ?");
        String obj = sb2.toString();
        A0J = obj;
        StringBuilder sb3 = new StringBuilder();
        sb3.append(obj);
        sb3.append(" AND ");
        sb3.append("message_type = ?");
        sb3.append(" ORDER BY sort_id DESC");
        A08 = sb3.toString();
        StringBuilder sb4 = new StringBuilder();
        sb4.append(obj);
        sb4.append(" AND ");
        sb4.append("message_type");
        sb4.append(" NOT IN ('");
        sb4.append(8);
        sb4.append("', '");
        sb4.append(10);
        sb4.append("', '");
        sb4.append(7);
        sb4.append("', '");
        sb4.append(15);
        sb4.append("', '");
        sb4.append(19);
        sb4.append("') AND ");
        sb4.append("from_me = 0");
        sb4.append(" ORDER BY sort_id DESC");
        sb4.append(" LIMIT ?");
        A05 = sb4.toString();
        StringBuilder sb5 = new StringBuilder();
        sb5.append(obj);
        sb5.append(" AND ");
        sb5.append("message_type");
        sb5.append(" NOT IN ('");
        sb5.append(8);
        sb5.append("', '");
        sb5.append(10);
        sb5.append("', '");
        sb5.append(7);
        sb5.append("', '");
        sb5.append(15);
        sb5.append("', '");
        sb5.append(19);
        sb5.append("') AND ");
        sb5.append("from_me = 1");
        sb5.append(" ORDER BY sort_id DESC");
        sb5.append(" LIMIT ?");
        A07 = sb5.toString();
        StringBuilder sb6 = new StringBuilder();
        sb6.append(obj);
        sb6.append(" AND ");
        sb6.append("message_type");
        sb6.append(" NOT IN ('");
        sb6.append(7);
        sb6.append("', '");
        sb6.append(15);
        sb6.append("', '");
        sb6.append(19);
        sb6.append("')");
        sb6.append(" AND (view_mode IS NULL OR view_mode = 0) ");
        sb6.append(" ORDER BY sort_id DESC");
        sb6.append(" LIMIT ?");
        A06 = sb6.toString();
        StringBuilder sb7 = new StringBuilder();
        sb7.append(obj);
        sb7.append(" AND ");
        sb7.append("(message_type != '8')");
        String obj2 = sb7.toString();
        StringBuilder sb8 = new StringBuilder();
        sb8.append(obj2);
        sb8.append(" AND ");
        sb8.append("_id >= ?");
        sb8.append(" ORDER BY _id ASC");
        A0A = sb8.toString();
        StringBuilder sb9 = new StringBuilder();
        sb9.append(obj2);
        sb9.append(" ORDER BY ");
        sb9.append("sort_id DESC");
        sb9.append(" LIMIT ?");
        A09 = sb9.toString();
        StringBuilder sb10 = new StringBuilder();
        sb10.append("   SELECT ");
        sb10.append(str);
        sb10.append(" FROM ");
        sb10.append("available_message_view");
        sb10.append(" WHERE ");
        sb10.append("_id >= ? ");
        sb10.append(" AND ");
        sb10.append("_id < ? ");
        sb10.append(" AND (view_mode IS NOT 1 AND view_mode IS NOT 3) ");
        sb10.append(" AND (expire_timestamp IS NULL OR expire_timestamp >= ? OR keep_in_chat = 1) ");
        sb10.append(" ORDER BY _id DESC");
        sb10.append(" LIMIT ? ");
        A0M = sb10.toString();
        StringBuilder sb11 = new StringBuilder();
        sb11.append("   SELECT ");
        sb11.append(str);
        sb11.append(" FROM ");
        sb11.append("available_message_view");
        sb11.append(" AS message  JOIN (  SELECT ");
        sb11.append("chat_view._id");
        sb11.append(" AS chat_view_table_id  FROM ");
        sb11.append("chat_view chat_view");
        sb11.append(" LEFT JOIN jid jid");
        sb11.append(" ON ");
        sb11.append("chat_view.jid_row_id");
        sb11.append(" = ");
        sb11.append("jid._id");
        sb11.append(" WHERE ");
        sb11.append("type NOT IN ( 1, 16, 3, 5, 6 )");
        sb11.append(" )AS chat");
        sb11.append(" ON message.chat_row_id = chat.chat_view_table_id");
        sb11.append(" WHERE ");
        sb11.append("_id >= ? ");
        sb11.append(" AND ");
        sb11.append("_id < ? ");
        sb11.append(" AND (view_mode IS NULL OR view_mode = 0) ");
        sb11.append(" AND (expire_timestamp IS NULL) ");
        sb11.append(" AND ");
        sb11.append("message_type");
        sb11.append(" NOT IN (");
        sb11.append(42);
        sb11.append(", ");
        sb11.append(43);
        sb11.append(", ");
        sb11.append(78);
        sb11.append(", ");
        sb11.append(82);
        sb11.append(") AND ");
        sb11.append("broadcast != 1");
        sb11.append(" ORDER BY _id DESC");
        sb11.append(" LIMIT ? ");
        A0L = sb11.toString();
        StringBuilder sb12 = new StringBuilder();
        sb12.append("   SELECT ");
        sb12.append(str);
        sb12.append(" FROM ");
        sb12.append("available_message_view");
        sb12.append(" WHERE ");
        sb12.append("_id > ? ");
        sb12.append(" AND ");
        sb12.append("_id <= ? ");
        sb12.append(" AND (expire_timestamp IS NULL OR expire_timestamp >= ? OR keep_in_chat = 1) ");
        sb12.append(" ORDER BY _id ASC");
        sb12.append(" LIMIT ? ");
        A0I = sb12.toString();
        StringBuilder sb13 = new StringBuilder();
        sb13.append("SELECT ");
        sb13.append(str);
        sb13.append(" FROM ");
        sb13.append("available_message_view");
        sb13.append(" WHERE ");
        sb13.append("timestamp >= ? ");
        sb13.append(" ORDER BY ");
        sb13.append("timestamp");
        sb13.append(" LIMIT 1");
        A0K = sb13.toString();
        StringBuilder sb14 = new StringBuilder();
        sb14.append("SELECT ");
        sb14.append(str);
        sb14.append(" FROM ");
        sb14.append("available_message_view");
        sb14.append(" WHERE ");
        sb14.append("chat_row_id = ?");
        sb14.append(" AND ");
        sb14.append("starred = 1");
        sb14.append(" AND ");
        sb14.append("(message_type != '7')");
        String obj3 = sb14.toString();
        StringBuilder sb15 = new StringBuilder();
        sb15.append(obj3);
        sb15.append(" ORDER BY ");
        sb15.append("sort_id");
        sb15.append(" DESC");
        A01 = sb15.toString();
        StringBuilder sb16 = new StringBuilder();
        sb16.append("SELECT ");
        sb16.append(str);
        sb16.append(" FROM ");
        sb16.append("available_message_view");
        sb16.append(" WHERE ");
        sb16.append("starred = 1");
        sb16.append(" AND ");
        sb16.append("(message_type != '7')");
        String obj4 = sb16.toString();
        StringBuilder sb17 = new StringBuilder();
        sb17.append(obj4);
        sb17.append(" ORDER BY ");
        sb17.append("timestamp");
        sb17.append(" DESC");
        A02 = sb17.toString();
        StringBuilder sb18 = new StringBuilder();
        sb18.append("SELECT ");
        sb18.append(str);
        sb18.append(" FROM ");
        sb18.append("available_message_view");
        sb18.append(" WHERE ");
        sb18.append("chat_row_id = ?");
        sb18.append(" AND ");
        sb18.append("_id IN (SELECT message_row_id FROM message_ephemeral WHERE keep_in_chat = 1)");
        String obj5 = sb18.toString();
        StringBuilder sb19 = new StringBuilder();
        sb19.append(obj5);
        sb19.append(" ORDER BY sort_id DESC");
        A00 = sb19.toString();
        StringBuilder sb20 = new StringBuilder();
        sb20.append("   SELECT ");
        sb20.append(str);
        sb20.append(" FROM ");
        sb20.append("available_message_view");
        sb20.append(" WHERE ");
        sb20.append("chat_row_id = ?");
        sb20.append(" AND ");
        sb20.append("sort_id > ?");
        sb20.append(" AND ");
        sb20.append("sort_id <= ?");
        sb20.append(" AND ");
        sb20.append("timestamp <= ? ");
        sb20.append(" AND ");
        sb20.append("message_type = 7");
        sb20.append(" AND (expire_timestamp IS NULL OR expire_timestamp >= ? OR keep_in_chat = 1) ");
        sb20.append(" ORDER BY sort_id DESC ");
        A0N = sb20.toString();
        StringBuilder sb21 = new StringBuilder();
        sb21.append("SELECT ");
        sb21.append(str);
        sb21.append(" FROM ");
        sb21.append("available_message_view");
        sb21.append(" WHERE ");
        sb21.append("_id = ?");
        A0B = sb21.toString();
        StringBuilder sb22 = new StringBuilder();
        sb22.append("SELECT ");
        sb22.append(str);
        sb22.append(" FROM ");
        sb22.append("available_message_view");
        sb22.append(" WHERE chat_row_id=? AND from_me=? AND key_id=?");
        A03 = sb22.toString();
        StringBuilder sb23 = new StringBuilder();
        sb23.append("SELECT ");
        sb23.append(str);
        sb23.append(" FROM ");
        sb23.append("available_message_view");
        sb23.append(" WHERE ");
        sb23.append("chat_row_id = ? AND ");
        sb23.append("_id <= ? ");
        sb23.append(" AND (view_mode IS NOT 1 AND view_mode IS NOT 3) ");
        sb23.append(" ORDER BY _id DESC ");
        sb23.append("LIMIT 1");
        A0C = sb23.toString();
        StringBuilder sb24 = new StringBuilder();
        sb24.append("SELECT ");
        sb24.append(str);
        sb24.append(" FROM ");
        sb24.append("available_message_view");
        sb24.append(" WHERE ");
        sb24.append("sort_id = ?");
        A0E = sb24.toString();
        StringBuilder sb25 = new StringBuilder();
        sb25.append("SELECT ");
        sb25.append(str);
        sb25.append(" FROM ");
        sb25.append("available_message_view");
        sb25.append(" WHERE ");
        sb25.append("sort_id = ?");
        sb25.append(" AND ");
        sb25.append("chat_row_id = ?");
        A0D = sb25.toString();
        StringBuilder sb26 = new StringBuilder();
        sb26.append("SELECT ");
        sb26.append(str);
        sb26.append(" FROM ");
        sb26.append("available_message_view");
        sb26.append(" WHERE ");
        sb26.append("chat_row_id = ?");
        sb26.append(" ORDER BY sort_id DESC");
        sb26.append(" LIMIT 1");
        A0H = sb26.toString();
        StringBuilder sb27 = new StringBuilder();
        sb27.append("SELECT ");
        sb27.append(str);
        sb27.append(" FROM ");
        sb27.append("available_message_view");
        sb27.append(" WHERE ");
        sb27.append("chat_row_id = ?");
        sb27.append(" AND ");
        sb27.append("message_type NOT IN ('8', '10', '90', '12', '98') ");
        sb27.append(" ORDER BY sort_id DESC");
        sb27.append(" LIMIT ?");
        A0F = sb27.toString();
        StringBuilder sb28 = new StringBuilder();
        sb28.append("SELECT ");
        sb28.append(str);
        sb28.append(" FROM ");
        sb28.append("available_message_view");
        sb28.append(" WHERE ");
        sb28.append("message_type IN ('9' , '26' )");
        sb28.append(" AND ");
        sb28.append("origin != 7");
        sb28.append(" AND ");
        sb28.append("chat_row_id = ?");
        sb28.append(" ORDER BY sort_id DESC");
        A04 = sb28.toString();
        StringBuilder sb29 = new StringBuilder();
        sb29.append("SELECT ");
        sb29.append(str);
        sb29.append(" FROM ");
        sb29.append("available_message_view");
        sb29.append(" WHERE ");
        sb29.append("message_type = 12");
        sb29.append(" ORDER BY _id");
        A0G = sb29.toString();
        StringBuilder sb30 = new StringBuilder();
        sb30.append("SELECT ");
        sb30.append(str);
        sb30.append(" FROM ");
        sb30.append("available_message_view");
        sb30.append(" WHERE ");
        sb30.append("from_me = 1");
        sb30.append(" AND ");
        sb30.append("status < 4");
        sb30.append(" AND ");
        sb30.append("_id > ?");
        sb30.append(" AND ");
        sb30.append("sort_id > 0");
        sb30.append(" ORDER BY _id ASC");
        A0O = sb30.toString();
    }

    public static String A00(int i) {
        if (i <= 0) {
            return " AND (view_mode IS NULL OR view_mode = 0) ";
        }
        StringBuilder sb = new StringBuilder();
        sb.append(" AND (view_mode IS NULL OR ");
        sb.append("view_mode IN ");
        sb.append(AnonymousClass1H2.A00(i));
        sb.append(") ");
        return sb.toString();
    }
}
