package X;

import android.content.Context;
import android.content.res.Resources;
import android.text.TextUtils;
import android.util.DisplayMetrics;
import android.util.TypedValue;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.LinearLayout;
import com.whatsapp.TextEmojiLabel;
import com.whatsapp.WaFrameLayout;
import com.whatsapp.WaImageView;
import com.whatsapp.WaTextView;
import com.whatsapp.stickers.StickerView;

/* renamed from: X.4GN  reason: invalid class name */
public abstract class AnonymousClass4GN {
    public static final WaFrameLayout A00(Context context, C108355bZ r16) {
        Resources resources = context.getResources();
        DisplayMetrics displayMetrics = resources.getDisplayMetrics();
        WaFrameLayout waFrameLayout = new WaFrameLayout(context);
        waFrameLayout.setId(2131434295);
        AnonymousClass3Ma.A18(waFrameLayout, -1, -2);
        waFrameLayout.setForeground(r16.BS0(AnonymousClass00R.A01, 2, false));
        LinearLayout linearLayout = new LinearLayout(context);
        AnonymousClass3Ma.A18(linearLayout, -1, -2);
        AnonymousClass3MY.A0v(context, linearLayout, 2131232548);
        linearLayout.setGravity(16);
        linearLayout.setMinimumHeight(AnonymousClass3MZ.A03(displayMetrics, 48.0f, 1));
        linearLayout.setMinimumWidth(AnonymousClass3MZ.A03(displayMetrics, 120.0f, 1));
        linearLayout.setOrientation(0);
        View view = new View(context);
        view.setId(2131434294);
        AnonymousClass3Ma.A18(view, resources.getDimensionPixelSize(2131168779), -1);
        linearLayout.addView(view);
        LinearLayout linearLayout2 = new LinearLayout(context);
        LinearLayout.LayoutParams layoutParams = new LinearLayout.LayoutParams(0, -2);
        layoutParams.weight = 1.0f;
        linearLayout2.setLayoutParams(layoutParams);
        linearLayout2.setOrientation(1);
        linearLayout2.setPadding(AnonymousClass3MZ.A03(displayMetrics, 8.0f, 1), AnonymousClass3MZ.A03(displayMetrics, 4.0f, 1), AnonymousClass3MZ.A03(displayMetrics, 8.0f, 1), AnonymousClass3MZ.A03(displayMetrics, 4.0f, 1));
        LinearLayout linearLayout3 = new LinearLayout(context);
        linearLayout3.setId(2131434308);
        LinearLayout.LayoutParams layoutParams2 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams2.gravity = 3;
        linearLayout3.setLayoutParams(layoutParams2);
        linearLayout3.setOrientation(0);
        TextEmojiLabel textEmojiLabel = new TextEmojiLabel(context);
        textEmojiLabel.setId(2131434307);
        AnonymousClass3Ma.A17(textEmojiLabel);
        TextUtils.TruncateAt truncateAt = TextUtils.TruncateAt.END;
        textEmojiLabel.setEllipsize(truncateAt);
        textEmojiLabel.setMaxLines(1);
        textEmojiLabel.setSingleLine();
        C72463Mc.A0y(context, textEmojiLabel, 2130971964, 2131103119);
        linearLayout3.addView(textEmojiLabel);
        WaTextView waTextView = new WaTextView(context);
        waTextView.setId(2131434293);
        AnonymousClass3Ma.A17(waTextView);
        waTextView.setEllipsize(truncateAt);
        waTextView.setMaxLines(1);
        waTextView.setSingleLine();
        waTextView.setPadding(AnonymousClass3MZ.A03(displayMetrics, 4.0f, 1), 0, AnonymousClass3MZ.A03(displayMetrics, 4.0f, 1), 0);
        waTextView.setText(2131898822);
        C72463Mc.A0y(context, waTextView, 2130971964, 2131103119);
        waTextView.setVisibility(8);
        linearLayout3.addView(waTextView);
        TextEmojiLabel textEmojiLabel2 = new TextEmojiLabel(context);
        textEmojiLabel2.setId(2131434304);
        AnonymousClass3Ma.A17(textEmojiLabel2);
        textEmojiLabel2.setEllipsize(truncateAt);
        textEmojiLabel2.setMaxLines(1);
        textEmojiLabel2.setSingleLine();
        textEmojiLabel2.setText(2131896303);
        C72463Mc.A0y(context, textEmojiLabel2, 2130971964, 2131103119);
        textEmojiLabel2.setVisibility(8);
        linearLayout3.addView(textEmojiLabel2);
        linearLayout2.addView(linearLayout3);
        FrameLayout frameLayout = new FrameLayout(context);
        AnonymousClass3Ma.A17(frameLayout);
        TextEmojiLabel textEmojiLabel3 = new TextEmojiLabel(context);
        textEmojiLabel3.setId(2131434305);
        FrameLayout.LayoutParams layoutParams3 = new FrameLayout.LayoutParams(-2, -2);
        layoutParams3.gravity = 3;
        textEmojiLabel3.setLayoutParams(layoutParams3);
        textEmojiLabel3.setEllipsize(truncateAt);
        C72463Mc.A0y(context, textEmojiLabel3, 2130971113, 2131102439);
        frameLayout.addView(textEmojiLabel3);
        StickerView stickerView = new StickerView(context);
        stickerView.setId(2131434302);
        FrameLayout.LayoutParams layoutParams4 = new FrameLayout.LayoutParams(resources.getDimensionPixelSize(2131168923), resources.getDimensionPixelSize(2131168923));
        int A03 = AnonymousClass3MZ.A03(displayMetrics, 2.0f, 1);
        layoutParams4.gravity = 3;
        layoutParams4.leftMargin = A03;
        layoutParams4.rightMargin = A03;
        layoutParams4.topMargin = A03;
        layoutParams4.bottomMargin = A03;
        stickerView.setLayoutParams(layoutParams4);
        stickerView.setVisibility(8);
        frameLayout.addView(stickerView);
        linearLayout2.addView(frameLayout);
        TextEmojiLabel textEmojiLabel4 = new TextEmojiLabel(context);
        textEmojiLabel4.setId(2131434303);
        LinearLayout.LayoutParams layoutParams5 = new LinearLayout.LayoutParams(-2, -2);
        layoutParams5.gravity = 3;
        textEmojiLabel4.setLayoutParams(layoutParams5);
        textEmojiLabel4.setEllipsize(TextUtils.TruncateAt.END);
        textEmojiLabel4.setMaxLines(2);
        C72463Mc.A0y(context, textEmojiLabel4, 2130971113, 2131102439);
        textEmojiLabel4.setVisibility(8);
        linearLayout2.addView(textEmojiLabel4);
        linearLayout.addView(linearLayout2);
        WaImageView waImageView = new WaImageView(context);
        waImageView.setId(2131434306);
        AnonymousClass3Ma.A18(waImageView, AnonymousClass3MZ.A03(displayMetrics, 52.0f, 1), -1);
        AnonymousClass3MW.A1R(waImageView);
        linearLayout.addView(waImageView);
        WaImageView waImageView2 = new WaImageView(context);
        waImageView2.setId(2131429433);
        AnonymousClass3Ma.A18(waImageView2, resources.getDimensionPixelSize(2131166219), resources.getDimensionPixelSize(2131166219));
        waImageView2.setScaleType(ImageView.ScaleType.FIT_CENTER);
        waImageView2.setVisibility(8);
        linearLayout.addView(waImageView2);
        FrameLayout frameLayout2 = new FrameLayout(context);
        frameLayout2.setId(2131434299);
        AnonymousClass3Ma.A18(frameLayout2, -2, -1);
        frameLayout2.setVisibility(8);
        WaImageView waImageView3 = new WaImageView(context);
        waImageView3.setId(2131434300);
        AnonymousClass3Ma.A18(waImageView3, AnonymousClass3MZ.A03(displayMetrics, 52.0f, 1), -1);
        AnonymousClass3MW.A1R(waImageView3);
        waImageView3.setVisibility(8);
        frameLayout2.addView(waImageView3);
        WaTextView waTextView2 = new WaTextView(context);
        waTextView2.setId(2131434301);
        FrameLayout.LayoutParams layoutParams6 = new FrameLayout.LayoutParams(-2, -1);
        layoutParams6.gravity = 17;
        waTextView2.setLayoutParams(layoutParams6);
        waTextView2.setMaxWidth(AnonymousClass3MZ.A03(displayMetrics, 88.0f, 1));
        waTextView2.setMinWidth(AnonymousClass3MZ.A03(displayMetrics, 44.0f, 1));
        waTextView2.setMinimumWidth(AnonymousClass3MZ.A03(displayMetrics, 44.0f, 1));
        waTextView2.setBackgroundResource(2131232803);
        waTextView2.setGravity(17);
        waTextView2.setPadding(AnonymousClass3MZ.A03(displayMetrics, 8.0f, 1), 0, AnonymousClass3MZ.A03(displayMetrics, 8.0f, 1), 0);
        waTextView2.setMaxLines(1);
        C29261bv.A04(waTextView2, 1);
        C29261bv.A09(waTextView2, AnonymousClass3MZ.A03(displayMetrics, 12.0f, 2), AnonymousClass3MZ.A03(displayMetrics, 20.0f, 2), AnonymousClass3MZ.A03(displayMetrics, 2.0f, 2), 0);
        AnonymousClass3MX.A1C(context, waTextView2, 2131102112);
        waTextView2.setTextSize(TypedValue.applyDimension(2, 14.0f, displayMetrics));
        frameLayout2.addView(waTextView2);
        linearLayout.addView(frameLayout2);
        waFrameLayout.addView(linearLayout);
        FrameLayout frameLayout3 = new FrameLayout(context);
        frameLayout3.setId(2131428811);
        FrameLayout.LayoutParams layoutParams7 = new FrameLayout.LayoutParams(-2, -2);
        layoutParams7.gravity = 53;
        frameLayout3.setLayoutParams(layoutParams7);
        AnonymousClass3MY.A0w(context, frameLayout3, 2131898783);
        frameLayout3.setPadding(AnonymousClass3MZ.A03(displayMetrics, 12.0f, 1), AnonymousClass3MZ.A03(displayMetrics, 2.0f, 1), AnonymousClass3MZ.A03(displayMetrics, 2.0f, 1), AnonymousClass3MZ.A03(displayMetrics, 12.0f, 1));
        frameLayout3.setVisibility(8);
        WaImageView waImageView4 = new WaImageView(context);
        waImageView4.setId(2131428823);
        waImageView4.setLayoutParams(new ViewGroup.LayoutParams(AnonymousClass3MZ.A03(displayMetrics, 16.0f, 1), AnonymousClass3MZ.A03(displayMetrics, 16.0f, 1)));
        waImageView4.setBackgroundResource(2131232950);
        waImageView4.setImageResource(2131231814);
        frameLayout3.addView(waImageView4);
        waFrameLayout.addView(frameLayout3);
        return waFrameLayout;
    }
}
