package X;

import java.util.Set;

public abstract class BVK extends C24704CGq {
    public static final Set A00;
    public static final Set A01;
    public static final Set A02;
    public static final Set A03;
    public static final Set A04 = BE8.A0r("com.instagram.lite", "com.instagram.barcelona", C17880vN.A1b("com.instagram.direct", "com.instagram.android", 4, 1), 2, 3);
    public static final Set A05;
    public static final Set A06;
    public static final Set A07;

    static {
        Set set = C24704CGq.A01;
        String[] strArr = new String[25];
        strArr[0] = "com.facebook.mk";
        strArr[1] = "com.oculus.horizon.dev";
        strArr[2] = "com.oculus.panelapp.settings";
        strArr[3] = "com.facebook.games";
        strArr[4] = "com.facebook.home.dev";
        strArr[5] = "com.facebook.bonfire";
        strArr[6] = "com.facebook.workdev";
        strArr[7] = "com.facebook.home";
        strArr[8] = "com.facebook.phone";
        strArr[9] = "com.facebook.stella_debug";
        strArr[10] = "com.facebook.mlite";
        strArr[11] = "com.facebook.akira";
        strArr[12] = "com.facebook.appmanager.dev";
        strArr[13] = "com.facebook.daykira";
        strArr[14] = "com.facebook.wearable.monza";
        strArr[15] = "com.instagram.direct";
        strArr[16] = "com.facebook.wakizashi";
        strArr[17] = "com.facebook.horizon";
        strArr[18] = "com.facebook.react.panelapp";
        strArr[19] = "com.facebook.together.together.stable";
        strArr[20] = "com.facebook.together.together.release_nightly";
        strArr[21] = "com.facebook.together.together.stable";
        strArr[22] = "com.facebook.together.together.staging";
        strArr[23] = "com.meta.mr.awe";
        A03 = C41841x9.A04(BE6.A15("com.oculus.vrshell.home", strArr, 24), set);
        Set set2 = C24704CGq.A00;
        String[] strArr2 = new String[8];
        strArr2[0] = "com.facebook.globalsecurity";
        strArr2[1] = "com.facebook.mlite_debug";
        strArr2[2] = "com.oculus.rooms";
        strArr2[3] = "com.facebook.horizon";
        strArr2[4] = "com.facebook.together.together.stable";
        strArr2[5] = "com.facebook.together.together.release_nightly";
        A02 = C41841x9.A04(BE8.A0r("com.facebook.together.together.stable", "com.facebook.together.together.staging", strArr2, 6, 7), set2);
        String[] strArr3 = new String[54];
        strArr3[0] = "com.facebook.adsmanager";
        strArr3[1] = "com.facebook.akira";
        strArr3[2] = "com.facebook.appmanager";
        strArr3[3] = "com.facebook.appmanager.dev";
        strArr3[4] = "com.facebook.arstudio.player";
        strArr3[5] = "com.facebook.assistantplayground";
        strArr3[6] = "com.facebook.bishop";
        strArr3[7] = "com.facebook.pages.app";
        strArr3[8] = "com.facebook.creatorstudio";
        strArr3[9] = "com.facebook.daykira";
        strArr3[10] = "com.instagram.direct";
        strArr3[11] = "com.facebook.lite";
        strArr3[12] = "com.facebook.games";
        strArr3[13] = "com.facebook.phone";
        strArr3[14] = "com.facebook.home";
        strArr3[15] = "com.facebook.home.dev";
        strArr3[16] = "com.instagram.android";
        strArr3[17] = "com.instagram.lite";
        strArr3[18] = "com.facebook.katana";
        strArr3[19] = "com.facebook.orca";
        strArr3[20] = "com.facebook.react.panelapp";
        BEA.A1G("com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", strArr3);
        strArr3[24] = "com.facebook.wearable.monza";
        strArr3[25] = "com.oculus.assistant";
        strArr3[26] = "com.oculus.vrshell";
        strArr3[27] = "com.oculus.firsttimenux";
        strArr3[28] = "com.oculus.horizon";
        strArr3[29] = "com.oculus.horizon.dev";
        strArr3[30] = "com.oculus.gemini.upload";
        strArr3[31] = "com.oculus.metacam";
        strArr3[32] = "com.oculus.panelapp.settings";
        strArr3[33] = "com.oculus.vrshell.home";
        strArr3[34] = "com.oculus.ocms";
        strArr3[35] = "com.oculus.systemutilities";
        strArr3[36] = "com.oculus.twilight";
        strArr3[37] = "com.oculus.userserver2";
        strArr3[38] = "com.oculus.updater";
        strArr3[39] = "com.oculus.systemux";
        strArr3[40] = "com.oculus.xrstreamingclient";
        strArr3[41] = "com.facebook.bonfire";
        strArr3[42] = "com.facebook.stella";
        strArr3[43] = "com.facebook.stella_debug";
        strArr3[44] = "com.facebook.study";
        strArr3[45] = "com.instagram.barcelona";
        strArr3[46] = "com.facebook.wakizashi";
        strArr3[47] = "com.whatsapp";
        strArr3[48] = "com.whatsapp.w4b";
        BEA.A1F("com.facebook.horizon", "com.facebook.together.together.stable", "com.facebook.together.together.release_nightly", strArr3);
        strArr3[52] = "com.facebook.together.together.stable";
        A01 = BE6.A15("com.facebook.together.together.staging", strArr3, 53);
        String[] A1b = C17880vN.A1b("com.facebook.adsmanager", "com.facebook.akira", 63, 1);
        A1b[2] = "com.facebook.appmanager";
        A1b[3] = "com.facebook.appmanager.dev";
        A1b[4] = "com.facebook.arstudio.player";
        A1b[5] = "com.facebook.assistantplayground";
        A1b[6] = "com.instagram.barcelona";
        A1b[7] = "com.facebook.bishop";
        A1b[8] = "com.facebook.pages.app";
        A1b[9] = "com.facebook.creatorstudio";
        A1b[10] = "com.facebook.daykira";
        A1b[11] = "com.instagram.direct";
        A1b[12] = "com.facebook.lite";
        A1b[13] = "com.facebook.games";
        A1b[14] = "com.facebook.phone";
        A1b[15] = "com.facebook.home";
        A1b[16] = "com.facebook.home.dev";
        A1b[17] = "com.instagram.android";
        A1b[18] = "com.instagram.lite";
        BE9.A1C("com.facebook.katana", "com.facebook.orca", A1b);
        C17900vP.A0S("com.facebook.react.panelapp", "com.facebook.talk", "com.facebook.mk", "com.facebook.mlite", A1b);
        A1b[25] = "com.facebook.wearable.system.data";
        A1b[26] = "com.facebook.wearable.apps.mwear";
        A1b[27] = "com.facebook.wearable.system.notification";
        A1b[28] = "com.facebook.wearable.monza";
        A1b[29] = "com.oculus.assistant";
        A1b[30] = "com.oculus.captionservice";
        C17900vP.A0U("com.oculus.vrshell", "com.oculus.firsttimenux", "com.oculus.horizon", "com.oculus.horizon.dev", A1b);
        A1b[35] = "com.oculus.gemini.upload";
        C17900vP.A0V("com.oculus.metacam", "com.oculus.panelapp.settings", "com.oculus.vrshell.home", "com.oculus.ocms", A1b);
        A1b[40] = "com.oculus.q4bservice";
        BEB.A18("com.oculus.systemutilities", "com.oculus.twilight", "com.oculus.userserver2", "com.oculus.updater", A1b);
        A1b[45] = "com.oculus.systemux";
        A1b[46] = "com.oculus.xrstreamingclient";
        A1b[47] = "com.oculus.companion.server";
        A1b[48] = "com.facebook.bonfire";
        BEA.A1F("com.facebook.stella", "com.facebook.stella_debug", "com.facebook.study", A1b);
        A1b[52] = "com.instagram.barcelona";
        A1b[53] = "com.facebook.wakizashi";
        A1b[54] = "com.facebook.wearable.system.launcher";
        A1b[55] = "com.whatsapp";
        Object obj = "com.whatsapp.w4b";
        BEB.A1B(obj, "com.facebook.horizon", "com.facebook.together.together.stable", "com.facebook.together.together.release_nightly", A1b);
        A1b[60] = "com.facebook.together.together.stable";
        A1b[61] = "com.facebook.together.together.staging";
        A00 = BE6.A15("com.facebook.react.panelapp", A1b, 62);
        String[] strArr4 = new String[3];
        strArr4[0] = "com.facebook.work";
        strArr4[1] = "com.facebook.workdev";
        A07 = BE6.A15("com.facebook.workchat", strArr4, 2);
        A06 = BE8.A0r("com.whatsapp", obj, new String[2], 0, 1);
        String[] strArr5 = new String[21];
        strArr5[0] = "com.oculus.assistant";
        strArr5[1] = "com.oculus.browser";
        strArr5[2] = "com.oculus.captionservice";
        strArr5[3] = "com.oculus.companion.server";
        strArr5[4] = "com.oculus.explore";
        strArr5[5] = "com.oculus.firsttimenux";
        strArr5[6] = "com.oculus.vrshell.home";
        strArr5[7] = "com.oculus.horizon";
        strArr5[8] = "com.oculus.horizon.dev";
        strArr5[9] = "com.oculus.metacam";
        strArr5[10] = "com.oculus.nux.ota";
        strArr5[11] = "com.oculus.ocms";
        strArr5[12] = "com.oculus.panelapp.settings";
        strArr5[13] = "com.oculus.updater";
        strArr5[14] = "com.oculus.q4bservice";
        strArr5[15] = "com.oculus.store";
        strArr5[16] = "com.oculus.systemux";
        strArr5[17] = "com.oculus.xrstreamingclient";
        strArr5[18] = "com.oculus.systemutilities";
        BE9.A1C("com.oculus.twilight", "com.oculus.userserver2", strArr5);
        A05 = C200410p.A0S(strArr5);
    }
}
