package X;

/* renamed from: X.6Ef  reason: invalid class name and case insensitive filesystem */
public final class C120566Ef extends C126256cR {
    public static final C120566Ef A00 = new C120566Ef();

    public C120566Ef() {
        super("WA_UNIT_TEST", "DEBUG_TOOL", "XFAM_CROSSPOSTING_NATIVE_AUTH_TOKEN_XCHANGE_GQL", "XFAM_CROSSPOSTING_FB_ACCOUNT_CACHE", "XFAM_CROSSPOSTING_DB_SQL", "XFAM_CROSSPOSTING_ELIGIBILITY_GQL", "XFAM_CROSSPOSTING_NATIVE_AUTH_UI", "XFAM_CROSSPOSTING_REQUEST_GQL", "XFAM_CROSSPOSTING_REQUEST_MANAGER", "XFAM_CROSSPOSTING_WEB_AUTH_PROFILE_DATA_FETCH_GQL", "XFAM_CROSSPOSTING_NATIVE_AUTH_PROFILE_DATA_FETCH_GQL", "XFAM_CROSSPOSTING_STATUS_PRIVACY_UI", "XFAM_CROSSPOSTING_UNLINKING_GRAPH_API");
    }
}
