package X;

public enum C15 implements E68 {
    STREAM_STOPPED_REASON_UNKNOWN(0),
    STREAM_STOPPED_REASON_USER_INITIATED(1),
    STREAM_STOPPED_REASON_SYSTEM_PREEMPT(2),
    STREAM_STOPPED_REASON_SYSTEM_SHUTDOWN(3),
    STREAM_STOPPED_REASON_BATTERY_LOW(4),
    STREAM_STOPPED_REASON_THERMAL_THRESHOLD(5),
    STREAM_STOPPED_REASON_INACTIVITY(6),
    STREAM_STOPPED_REASON_CAMERA_FAILURE(7),
    STREAM_STOPPED_REASON_DOFF(8),
    STREAM_STOPPED_REASON_CLOSE_ARMS(9),
    STREAM_STOPPED_REASON_AUDIO_FAILURE(10),
    STREAM_STOPPED_REASON_MOBILE_STREAM_ERROR(11),
    STREAM_STOPPED_REASON_PEAK_POWER_INTERRUPT(12),
    STREAM_STOPPED_REASON_USER_PAUSE(13),
    STREAM_STOPPED_REASON_TAMPER_DETECTED(14),
    STREAM_STOPPED_REASON_HARDWARE_TOGGLE(15),
    STREAM_STOPPED_REASON_SYSTEM_SHUTDOWN_BATTERY(16),
    STREAM_STOPPED_REASON_FRAME_INITIATED(17),
    STREAM_STOPPED_REASON_CLIENT_PREEMPT(18),
    STREAM_STOPPED_REASON_VERSION_NOT_SUPPORTED(19),
    STREAM_STOPPED_REASON_CLIENT_INITIATED(20),
    STREAM_STOPPED_REASON_COMPANION_DEVICE_REQUESTED_SERVICE_STOP(21),
    STREAM_STOPPED_REASON_WEAK_SIGNAL(22),
    UNRECOGNIZED(-1);
    
    public final int value;

    public final int BVW() {
        if (this != UNRECOGNIZED) {
            return this.value;
        }
        throw BE7.A0X();
    }

    /* access modifiers changed from: public */
    C15(int i) {
        this.value = i;
    }
}
