package X;

/* renamed from: X.Bz4  reason: case insensitive filesystem */
public enum C24307Bz4 {
    EFFECT_FETCH_STARTED,
    EFFECT_FETCH_SUCCESS,
    EFFECT_FETCH_FAILED,
    EFFECT_RENDER_SET,
    EFFECT_RENDER_STARTED,
    EFFECT_FIRST_FRAME_RENDERED,
    EFFECT_RENDER_RECUR,
    EFFECT_RENDER_FAILED,
    EFFECT_RENDER_STOPPED,
    AVATAR_FETCH_STARTED,
    AVATAR_FETCH_COMPLETED,
    AVATAR_FETCH_FAILED,
    AVATAR_FIRST_FRAME_COLORIZATION_APPLIED,
    AVATAR_COLORIZATION_FAILED,
    AVATAR_DYNAMIC_COLOR_APPLIED,
    AVATAR_RENDERED,
    AVATAR_LOADED_VIA_AR_EFFECT;

    /* access modifiers changed from: public */
    static {
        C24307Bz4[] bz4Arr;
        A00 = C19780yz.A00(bz4Arr);
    }
}
