package X;

/* renamed from: X.Bz2  reason: case insensitive filesystem */
public enum C24305Bz2 {
    EDITOR_SCREEN_PREVIEW_EFFECT_LOAD_START,
    EDITOR_SCREEN_PREVIEW_EFFECT_LOAD_END,
    EDITOR_SCREEN_PREVIEW_EFFECT_LOAD_FAILED,
    EDITOR_SCREEN_PREVIEW_AVATAR_LOAD_START,
    EDITOR_SCREEN_PREVIEW_AVATAR_LOAD_END,
    EDITOR_SCREEN_PREVIEW_AVATAR_LOAD_FAILED,
    EDITOR_SCREEN_PREVIEW_NOT_ON_SUPPORTED_NETWORK,
    EDITOR_SCREEN_PREVIEW_RENDERING_TIMEOUT,
    EDITOR_SCREEN_PREVIEW_INITIAL_CHECK_FAILED,
    EDITOR_SCREEN_PREVIEW_NOT_ON_SUPPORTED_NETWORK_INITIAL,
    EDITOR_SCREEN_PREVIEW_LOW_MEMORY;

    /* access modifiers changed from: public */
    static {
        C24305Bz2[] bz2Arr;
        A00 = C19780yz.A00(bz2Arr);
    }
}
