package X;

import androidx.credentials.playservices.controllers.CreatePublicKeyCredential.PublicKeyCredentialControllerUtility;
import java.util.Collections;

/* renamed from: X.CfW  reason: case insensitive filesystem */
public abstract class C25424CfW {
    public static final AnonymousClass00P A00;

    /* JADX WARNING: type inference failed for: r3v0, types: [X.00O, X.00P] */
    static {
        Boolean bool = C17960vV.A01;
        ? r3 = new AnonymousClass00O(59);
        A00 = r3;
        String[] strArr = new String[2];
        strArr[0] = "ZA";
        r3.put("af", AnonymousClass8BR.A15("NA", strArr, 1));
        String[] strArr2 = new String[4];
        strArr2[0] = "EG";
        strArr2[1] = "SA";
        strArr2[2] = "SY";
        r3.put("ar", AnonymousClass8BR.A15("IQ", strArr2, 3));
        String[] strArr3 = new String[5];
        strArr3[0] = "AL";
        strArr3[1] = "XK";
        strArr3[2] = "GR";
        strArr3[3] = "MK";
        r3.put("sq", AnonymousClass8BR.A15("IT", strArr3, 4));
        r3.put("az", Collections.singletonList("AZ"));
        String[] strArr4 = new String[2];
        strArr4[0] = "IN";
        r3.put("bn", AnonymousClass8BR.A15("BD", strArr4, 1));
        r3.put("bg", Collections.singletonList("BG"));
        String[] strArr5 = new String[2];
        strArr5[0] = "ES";
        r3.put("ca", AnonymousClass8BR.A15("AD", strArr5, 1));
        String[] strArr6 = new String[4];
        strArr6[0] = "MY";
        strArr6[1] = "SG";
        strArr6[2] = "CN";
        r3.put("zh-Hans", AnonymousClass8BR.A15("HK", strArr6, 3));
        String[] strArr7 = new String[4];
        strArr7[0] = "HK";
        strArr7[1] = "TW";
        strArr7[2] = "MY";
        r3.put("zh-Hant", AnonymousClass8BR.A15("MO", strArr7, 3));
        String[] strArr8 = new String[2];
        strArr8[0] = "HR";
        r3.put("hr", AnonymousClass8BR.A15("BA", strArr8, 1));
        r3.put("cs", Collections.singletonList("CZ"));
        r3.put("da", Collections.singletonList("DK"));
        String[] strArr9 = new String[3];
        strArr9[0] = "NL";
        strArr9[1] = "BE";
        r3.put("nl", AnonymousClass8BR.A15("SR", strArr9, 2));
        String[] strArr10 = new String[5];
        strArr10[0] = "IN";
        strArr10[1] = "PK";
        strArr10[2] = "ZA";
        strArr10[3] = "GB";
        r3.put("en", AnonymousClass8BR.A15("US", strArr10, 4));
        r3.put("et", Collections.singletonList("EE"));
        r3.put("fil", Collections.singletonList("PH"));
        r3.put("fi", Collections.singletonList("FI"));
        r3.put("fr", Collections.singletonList("FR"));
        String[] strArr11 = new String[3];
        strArr11[0] = "DE";
        strArr11[1] = "AT";
        r3.put("de", AnonymousClass8BR.A15("CH", strArr11, 2));
        String[] strArr12 = new String[2];
        strArr12[0] = "GR";
        r3.put("el", AnonymousClass8BR.A15("CY", strArr12, 1));
        A00(r3, "IN", "gu");
        r3.put("he", Collections.singletonList("IL"));
        A00(r3, "IN", "hi");
        String[] strArr13 = new String[2];
        strArr13[0] = "HU";
        r3.put("hu", AnonymousClass8BR.A15("RO", strArr13, 1));
        r3.put(PublicKeyCredentialControllerUtility.JSON_KEY_ID, Collections.singletonList("ID"));
        String[] strArr14 = new String[2];
        strArr14[0] = "IE";
        r3.put("ga", AnonymousClass8BR.A15("GB", strArr14, 1));
        String[] strArr15 = new String[2];
        strArr15[0] = "IT";
        r3.put("it", AnonymousClass8BR.A15("CH", strArr15, 1));
        r3.put("ja", Collections.singletonList("JP"));
        A00(r3, "IN", "kn");
        String[] strArr16 = new String[3];
        strArr16[0] = "KZ";
        strArr16[1] = "UZ";
        r3.put("kk", AnonymousClass8BR.A15("MN", strArr16, 2));
        r3.put("ko", Collections.singletonList("KR"));
        r3.put("lo", Collections.singletonList("LA"));
        r3.put("lv", Collections.singletonList("LV"));
        r3.put("lt", Collections.singletonList("LT"));
        A00(r3, "MK", "mk");
        A00(r3, "MY", "ms");
        A00(r3, "IN", "ml");
        A00(r3, "IN", "mr");
        r3.put("nb", Collections.singletonList("NO"));
        String[] strArr17 = new String[2];
        strArr17[0] = "IR";
        r3.put("fa", AnonymousClass8BR.A15("AF", strArr17, 1));
        r3.put("pl", Collections.singletonList("PL"));
        r3.put("pt-BR", Collections.singletonList("BR"));
        String[] strArr18 = new String[4];
        strArr18[0] = "PT";
        strArr18[1] = "AO";
        strArr18[2] = "BR";
        r3.put("pt-PT", AnonymousClass8BR.A15("MZ", strArr18, 3));
        A00(r3, "IN", "pa");
        String[] strArr19 = new String[2];
        strArr19[0] = "RO";
        r3.put("ro", AnonymousClass8BR.A15("MD", strArr19, 1));
        String[] strArr20 = new String[4];
        strArr20[0] = "RU";
        strArr20[1] = "KZ";
        strArr20[2] = "KG";
        r3.put("ru", AnonymousClass8BR.A15("UA", strArr20, 3));
        String[] strArr21 = new String[3];
        strArr21[0] = "RS";
        strArr21[1] = "BA";
        r3.put("sr", AnonymousClass8BR.A15("ME", strArr21, 2));
        r3.put("sk", Collections.singletonList("SK"));
        r3.put("sl", Collections.singletonList("SI"));
        String[] strArr22 = new String[6];
        strArr22[0] = "MX";
        strArr22[1] = "AR";
        strArr22[2] = "CL";
        strArr22[3] = "CO";
        strArr22[4] = "ES";
        r3.put("es", AnonymousClass8BR.A15("PE", strArr22, 5));
        String[] strArr23 = new String[4];
        strArr23[0] = "TZ";
        strArr23[1] = "KE";
        strArr23[2] = "RW";
        r3.put("sw", AnonymousClass8BR.A15("BI", strArr23, 3));
        String[] strArr24 = new String[2];
        strArr24[0] = "SE";
        r3.put("sv", AnonymousClass8BR.A15("FI", strArr24, 1));
        String[] strArr25 = new String[4];
        strArr25[0] = "IN";
        strArr25[1] = "LK";
        strArr25[2] = "MY";
        r3.put("ta", AnonymousClass8BR.A15("SG", strArr25, 3));
        A00(r3, "IN", "te");
        String[] strArr26 = new String[2];
        strArr26[0] = "TH";
        r3.put("th", AnonymousClass8BR.A15("LA", strArr26, 1));
        r3.put("tr", Collections.singletonList("TR"));
        r3.put("uk", Collections.singletonList("UA"));
        String[] strArr27 = new String[2];
        strArr27[0] = "PK";
        r3.put("ur", AnonymousClass8BR.A15("IN", strArr27, 1));
        String[] A1b = C17880vN.A1b("UZ", "RU", 4, 1);
        A1b[2] = "KZ";
        r3.put("uz", AnonymousClass8BR.A15("KG", A1b, 3));
        r3.put("vi", Collections.singletonList("VN"));
    }

    public static void A00(AnonymousClass00O r1, Object obj, Object obj2) {
        r1.put(obj2, Collections.singletonList(obj));
    }
}
