package X;

/* renamed from: X.2Wp  reason: invalid class name and case insensitive filesystem */
public abstract class C51002Wp {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    @Deprecated
    public static final String A09;
    public static final String A0A;
    @Deprecated
    public static final String A0B;
    @Deprecated
    public static final String A0C;

    static {
        StringBuilder A10 = AnonymousClass000.A10();
        A10.append("SELECT ");
        String str = C209514c.A00;
        A10.append(str);
        A10.append(" FROM ");
        String A0Y = C17890vO.A0Y("message", A10);
        A10.append("sort_id");
        A10.append(" IN (SELECT docid FROM ");
        A10.append("message_ftsv2");
        A10.append(" AS ");
        A10.append("message_ftsv2");
        A10.append(", ");
        A10.append("available_message_view");
        A10.append(" AS message  WHERE ");
        A10.append("message_ftsv2");
        A10.append(" MATCH ? AND ");
        A10.append("message_ftsv2.docid = message.sort_id) ");
        A10.append(" ORDER BY ");
        A10.append("sort_id");
        A03 = AnonymousClass000.A0y(" DESC", A10);
        StringBuilder A0H = C17900vP.A0H("SELECT ", str, ", ");
        A0H.append("docid");
        A0H.append(", ");
        A0H.append("content");
        A0H.append(", ");
        A0H.append("fts_jid");
        A0H.append(" FROM ");
        A0H.append("message_ftsv2 AS fts");
        A0H.append(" JOIN ");
        A0H.append("available_message_view AS message");
        A0H.append(A0Y);
        String A0X = C17890vO.A0X("fts.docid = message.sort_id", A0H);
        A0H.append("message_ftsv2");
        A07 = AnonymousClass000.A0y(" MATCH ? ", A0H);
        StringBuilder A102 = AnonymousClass000.A10();
        C17900vP.A0c("SELECT ", str, ", ", "docid", A102);
        A102.append(", ");
        C17900vP.A0c("content", ", ", "fts_jid", " FROM ", A102);
        C17890vO.A10("message_ftsv2 AS fts", " JOIN ", "available_message_view AS message", A102);
        C17900vP.A0c(" ON ", "fts.docid = message.sort_id", A0Y, "message_ftsv2", A102);
        A06 = AnonymousClass000.A0y(" MATCH ? ", A102);
        StringBuilder A11 = AnonymousClass000.A11("SELECT ");
        AnonymousClass1H2.A02("message", A11, C209514c.A01);
        A11.append(", links.link_index AS link_index FROM ");
        A11.append("available_message_view AS message");
        A11.append(" INNER JOIN ");
        A11.append("message_link AS links");
        A11.append(" ON message.");
        A11.append("_id");
        A11.append(" = links.");
        A11.append("message_row_id");
        A11.append(" WHERE message.");
        A11.append("sort_id");
        A11.append(" IN ");
        A11.append("(SELECT docid FROM message_ftsv2 WHERE message_ftsv2 MATCH ? )");
        A02 = AnonymousClass000.A0y(" ORDER BY sort_id DESC", A11);
        StringBuilder A103 = AnonymousClass000.A10();
        C17900vP.A0c("SELECT ", str, " FROM ", "available_message_view", A103);
        A103.append(A0Y);
        A103.append("sort_id");
        A103.append(" IN ");
        A0A = AnonymousClass001.A1H("(SELECT docid FROM message_ftsv2 AS messages_fts, message AS message WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id AND message.starred = 1 AND (message_type != '7'))", " ORDER BY sort_id DESC", A103);
        StringBuilder A104 = AnonymousClass000.A10();
        C17900vP.A0c("SELECT ", str, " FROM ", "message", A104);
        A104.append(A0Y);
        A104.append("_id");
        A104.append(" IN (SELECT docid FROM ");
        A104.append("messages_fts");
        A104.append(" AS messages_fts, ");
        A104.append("available_message_view");
        A104.append(" AS message  WHERE content MATCH ? AND messages_fts.docid = message.");
        A104.append("_id");
        A104.append(" AND message.");
        A104.append("message_type");
        A104.append(" IN ('");
        A104.append(9);
        A104.append("' , '");
        A104.append(26);
        A104.append("' ) AND ");
        C17900vP.A0c("message.chat_row_id = ?) ", " ORDER BY ", "sort_id", " DESC", A104);
        A00 = A104.toString();
        StringBuilder A0H2 = C17900vP.A0H("SELECT ", str, ", links.link_index AS link_index FROM ");
        A0H2.append("message AS message");
        A0H2.append(", ");
        A0H2.append("(SELECT message_row_id, link_index FROM message_link AS link WHERE link.chat_row_id=? AND message_row_id IN ( SELECT docid FROM messages_fts, available_message_view AS message WHERE content MATCH ? AND messages_fts.docid = message._id)) links");
        A0H2.append(A0Y);
        A0H2.append("message._id = links.message_row_id ");
        A01 = AnonymousClass000.A0y(" ORDER BY _id DESC", A0H2);
        StringBuilder A112 = AnonymousClass000.A11(str);
        A112.append(", ");
        A112.append("messages_fts.docid AS docid");
        A112.append(", ");
        String A0y = AnonymousClass000.A0y("messages_fts.content AS content", A112);
        StringBuilder A0H3 = C17900vP.A0H("SELECT ", A0y, " FROM ");
        A0H3.append("message AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message.sort_id");
        A05 = AnonymousClass000.A0y(" WHERE content MATCH ?", A0H3);
        StringBuilder A0H4 = C17900vP.A0H("SELECT ", A0y, " FROM ");
        A0H4.append("available_message_view AS message JOIN messages_fts AS messages_fts ON messages_fts.docid = message.sort_id");
        A0H4.append(" WHERE content MATCH ? AND ");
        A04 = AnonymousClass000.A0y("chat_row_id = ?", A0H4);
        StringBuilder A105 = AnonymousClass000.A10();
        C17900vP.A0c("SELECT ", str, " FROM ", "message", A105);
        A105.append(A0Y);
        A105.append("_id");
        A105.append(" IN ");
        A0B = AnonymousClass001.A1H("( \n   SELECT docid \n   FROM messages_fts AS messages_fts, available_message_view AS message \n   WHERE content MATCH ? AND messages_fts.docid = message._id\n   AND message.starred = 1 AND (message_type != '7'))\n", " ORDER BY _id DESC", A105);
        StringBuilder A106 = AnonymousClass000.A10();
        C17900vP.A0c("SELECT ", str, " FROM ", "message", A106);
        A106.append(A0Y);
        A106.append("sort_id");
        A106.append(" IN ");
        C17900vP.A0c("( \n   SELECT docid \n   FROM message_ftsv2 AS messages_fts, available_message_view AS message \n   WHERE messages_fts.content MATCH ? AND messages_fts.docid = message.sort_id\n   AND message.starred = 1   AND (message_type != '7'))\n", " ORDER BY ", "sort_id", " DESC", A106);
        A0C = A106.toString();
        StringBuilder A107 = AnonymousClass000.A10();
        C17900vP.A0c("SELECT ", str, " FROM ", "available_message_view", A107);
        A107.append(A0Y);
        A107.append("_id");
        A107.append(" IN ");
        A09 = AnonymousClass001.A1H("(SELECT docid FROM messages_fts AS messages_fts, message AS message WHERE chat_row_id = ? AND messages_fts.content MATCH ? AND messages_fts.docid = message._id AND message.starred = 1 AND (message_type != '7'))", " ORDER BY _id DESC", A107);
        StringBuilder A108 = AnonymousClass000.A10();
        C17900vP.A0c("SELECT ", str, " FROM ", "available_message_view AS message", A108);
        A108.append(A0Y);
        A108.append("sort_id");
        A108.append(" IN ");
        A108.append("(SELECT docid FROM message_ftsv2 AS messages_fts, message AS message WHERE message_ftsv2 MATCH ? AND messages_fts.docid = message.sort_id)");
        A108.append(A0X);
        A108.append("message.keep_in_chat = 1");
        A108.append(A0X);
        A08 = AnonymousClass001.A1H("(message_type != '7')", " ORDER BY sort_id DESC", A108);
    }
}
