package X;

/* renamed from: X.2Wq  reason: invalid class name and case insensitive filesystem */
public abstract class C51012Wq {
    public static final String A00;
    public static final String A01;
    public static final String A02;
    public static final String A03;
    public static final String A04;
    public static final String A05;
    public static final String A06;
    public static final String A07;
    public static final String A08;
    public static final String A09;
    public static final String A0A;
    public static final String A0B;
    public static final String A0C;
    public static final String A0D;
    public static final String A0E;
    public static final String A0F;
    public static final String A0G;
    public static final String A0H;
    public static final String A0I;
    public static final String A0J;
    public static final String[] A0K;

    static {
        String[] strArr = {"message_row_id", "chat_row_id", "autotransfer_retry_enabled", "multicast_id", "media_job_uuid", "transferred", "transcoded", "file_path", "file_size", "suspicious_content", "trim_from", "trim_to", "face_x", "face_y", "media_key", "media_key_timestamp", "width", "height", "has_streaming_sidecar", "gif_attribution", "thumbnail_height_width_ratio", "direct_path", "first_scan_sidecar", "first_scan_length", "message_url", "mime_type", "file_length", "media_name", "file_hash", "media_duration", "page_count", "enc_file_hash", "partial_media_hash", "partial_media_enc_hash", "is_animated_sticker", "original_file_hash", "mute_video", "media_caption", "media_upload_handle", "sticker_flags", "raw_transcription_text", "first_viewed_timestamp"};
        A0K = strArr;
        StringBuilder A10 = AnonymousClass000.A10();
        A10.append("SELECT ");
        String[] strArr2 = C209514c.A01;
        AnonymousClass1H2.A02("message", A10, strArr2);
        A10.append(" FROM ");
        A10.append("available_message_view AS message");
        A10.append(" LEFT JOIN ");
        A10.append("chat_view");
        A10.append(" AS chat ON message.");
        A10.append("chat_row_id");
        A10.append(" = chat.");
        String A0Y = C17890vO.A0Y("_id", A10);
        A10.append("message.message_type IN ('2', '1', '25', '3', '81', '28', '13', '29', '9', '105', '26')");
        A10.append(" AND (chat.chat_lock = 0");
        A02 = AnonymousClass000.A0y(" OR chat.chat_lock is NULL)", A10);
        StringBuilder A11 = AnonymousClass000.A11("SELECT ");
        AnonymousClass1H2.A02("message", A11, strArr2);
        C17890vO.A10(", ", "file_size", " FROM ", A11);
        A11.append("message_media AS message_media");
        A11.append(" JOIN ");
        A11.append("available_message_view AS message");
        C17900vP.A0c(" ON message_media.message_row_id = message._id", " LEFT JOIN ", "chat_view", " AS chat ON message.", A11);
        C17900vP.A0c("chat_row_id", " = chat.", "_id", A0Y, A11);
        C17890vO.A10("message_type IN ('2', '1', '25', '3', '81', '28', '13', '29', '9', '105', '26')", " AND (chat.chat_lock = 0", " OR chat.chat_lock is NULL)", A11);
        A00 = A11.toString();
        StringBuilder A112 = AnonymousClass000.A11("SELECT ");
        C17900vP.A0c(AnonymousClass1H2.A01("message", strArr2), ", ", "file_size", " FROM ", A112);
        C17900vP.A0c("message_media AS message_media", " JOIN ", "available_message_view AS message", " LEFT JOIN ", A112);
        C17900vP.A0c("chat_view", " AS chat ON message.", "chat_row_id", " = chat.", A112);
        A112.append("_id");
        A112.append(" WHERE message_media.message_row_id = message._id");
        C17900vP.A0c(" AND ", "message_type IN ('2', '1', '25', '3', '81', '28', '13', '29', '9', '105', '26')", " AND (chat.chat_lock = 0", " OR chat.chat_lock is NULL)", A112);
        A01 = A112.toString();
        StringBuilder A113 = AnonymousClass000.A11("SELECT ");
        String str = C209514c.A00;
        A113.append(str);
        A113.append(", remove_files  FROM ");
        A113.append("deleted_messages_view");
        A113.append(A0Y);
        C17890vO.A10("message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " AND ", "chat_row_id", A113);
        A03 = AnonymousClass000.A0y(" = ?", A113);
        StringBuilder A0H2 = C17900vP.A0H("SELECT ", str, " FROM ");
        C17900vP.A0c("available_message_view", A0Y, "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " AND ", A0H2);
        A0H2.append("( NOT (message_type == 2 AND origin == 1)  OR (origin != 1))");
        A0H2.append(" AND ");
        A0H2.append("chat_row_id = ?");
        A08 = AnonymousClass000.A0y(" ORDER BY sort_id DESC", A0H2);
        StringBuilder A102 = AnonymousClass000.A10();
        C17900vP.A0c("SELECT ", str, " FROM ", "available_message_view", A102);
        A102.append(A0Y);
        A102.append("+message_type in (2 , 1 , 25 , 3 , 28 , 13 , 29 , 20 , 9 , 26 , 23 , 37 ) ");
        A102.append(" AND ");
        A102.append("from_me = 0");
        A102.append(" AND ");
        A102.append("sort_id > ? ");
        A0H = AnonymousClass000.A0y(" ORDER BY sort_id ASC", A102);
        StringBuilder A114 = AnonymousClass000.A11("SELECT ");
        C17900vP.A0c(AnonymousClass1H2.A01("message", strArr2), " FROM ", "message_media AS message_media", " JOIN ", A114);
        A114.append("available_message_view AS message");
        A114.append(" ON message_media.message_row_id = message._id");
        A114.append(A0Y);
        C17900vP.A0c("message_media.file_hash = ?", " AND ", "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " ORDER BY sort_id DESC", A114);
        A06 = AnonymousClass000.A0y(" LIMIT 1000", A114);
        StringBuilder A115 = AnonymousClass000.A11("SELECT ");
        C17900vP.A0c(AnonymousClass1H2.A01("message", strArr2), " FROM ", "message_media AS message_media", " JOIN ", A115);
        C17900vP.A0c("available_message_view AS message", " WHERE message_media.message_row_id = message._id", " AND ", "message_media.file_hash = ?", A115);
        C17900vP.A0c(" AND ", "message_type in ('2' , '1' , '25' , '3' , '28' , '13' , '29' , '20' , '9' , '26' , '23' , '37' ) ", " ORDER BY sort_id DESC", " LIMIT 1000", A115);
        A07 = A115.toString();
        StringBuilder A116 = AnonymousClass000.A11("SELECT ");
        C17900vP.A0c(AnonymousClass1H2.A01("message", strArr2), " FROM ", "message_media AS message_media", " JOIN ", A116);
        C17900vP.A0c("available_message_view AS message", " ON message_media.message_row_id = message._id", A0Y, "message_media.file_hash = ?", A116);
        A116.append(" AND ");
        C17890vO.A10("message.message_type = ?", " ORDER BY sort_id DESC", " LIMIT 1000", A116);
        A04 = A116.toString();
        StringBuilder A117 = AnonymousClass000.A11("SELECT ");
        C17900vP.A0c(AnonymousClass1H2.A01("message", strArr2), " FROM ", "message_media AS message_media", " JOIN ", A117);
        C17900vP.A0c("available_message_view AS message", " WHERE message_media.message_row_id = message._id", " AND ", "message_media.file_hash = ?", A117);
        C17900vP.A0c(" AND ", "message.message_type = ?", " ORDER BY sort_id DESC", " LIMIT 1000", A117);
        A05 = A117.toString();
        StringBuilder A103 = AnonymousClass000.A10();
        A103.append("SELECT message_media.*, ");
        AnonymousClass1H2.A02("message", A103, new String[]{"timestamp"});
        A103.append(",");
        C17900vP.A0c(AnonymousClass1H2.A01("message", new String[]{"message_type"}), " FROM ", "message_media AS message_media", " JOIN ", A103);
        A103.append("available_message_view AS message");
        A103.append(" ON message_media.message_row_id = message._id");
        A103.append(A0Y);
        A103.append("file_hash = ?");
        A103.append(" AND ");
        A103.append("enc_file_hash IS NOT NULL");
        A0D = AnonymousClass000.A0y(" ORDER BY message_row_id DESC", A103);
        StringBuilder A118 = AnonymousClass000.A11("SELECT message_media.*, ");
        AnonymousClass1H2.A02("message", A118, C17880vN.A1a("timestamp", 0));
        A118.append(",");
        C17900vP.A0c(AnonymousClass1H2.A01("message", C17880vN.A1a("message_type", 0)), " FROM ", "message_media AS message_media", " JOIN ", A118);
        C17900vP.A0c("available_message_view AS message", " WHERE message_media.message_row_id = message._id", " AND ", "file_hash = ?", A118);
        A118.append(" AND ");
        A0E = AnonymousClass001.A1H("enc_file_hash IS NOT NULL", " ORDER BY message_row_id DESC", A118);
        StringBuilder A119 = AnonymousClass000.A11("SELECT message_media.*, ");
        AnonymousClass1H2.A02("message", A119, C17880vN.A1a("timestamp", 0));
        A119.append(",");
        C17900vP.A0c(AnonymousClass1H2.A01("message", C17880vN.A1a("message_type", 0)), " FROM ", "message_media AS message_media", " JOIN ", A119);
        C17900vP.A0c("available_message_view AS message", " ON message_media.message_row_id = message._id", A0Y, "file_hash = ?", A119);
        A119.append(" AND ");
        C17900vP.A0c("enc_file_hash IS NOT NULL", " AND ", "message.message_type = ?", " ORDER BY sort_id DESC", A119);
        A0B = A119.toString();
        StringBuilder A1110 = AnonymousClass000.A11("SELECT message_media.*, ");
        AnonymousClass1H2.A02("message", A1110, C17880vN.A1a("timestamp", 0));
        A1110.append(",");
        C17900vP.A0c(AnonymousClass1H2.A01("message", C17880vN.A1a("message_type", 0)), " FROM ", "message_media AS message_media", " JOIN ", A1110);
        C17900vP.A0c("available_message_view AS message", " WHERE message_media.message_row_id = message._id", " AND ", "file_hash = ?", A1110);
        A1110.append(" AND ");
        C17900vP.A0c("enc_file_hash IS NOT NULL", " AND ", "message.message_type = ?", " ORDER BY sort_id DESC", A1110);
        A0C = A1110.toString();
        StringBuilder A1111 = AnonymousClass000.A11("SELECT message_media.*, ");
        C17900vP.A0c(AnonymousClass1H2.A01("message", new String[]{"chat_row_id", "from_me", "key_id"}), " FROM ", "message_media AS message_media", " JOIN ", A1111);
        C17900vP.A0c("available_message_view AS message", " ON message_media.message_row_id = message._id", A0Y, "file_hash = ?", A1111);
        A1111.append(" AND ");
        A1111.append("enc_file_hash = ?");
        A1111.append(" AND ");
        A1111.append("message_type in ('3', '1' ) ");
        A1111.append(" ORDER BY sort_id DESC");
        A0F = AnonymousClass000.A0y(" LIMIT 10", A1111);
        StringBuilder A1112 = AnonymousClass000.A11("SELECT message_media.*, ");
        C17900vP.A0c(AnonymousClass1H2.A01("message", new String[]{"chat_row_id", "from_me", "key_id"}), " FROM ", "message_media AS message_media", " JOIN ", A1112);
        C17900vP.A0c("available_message_view AS message", " WHERE message_media.message_row_id = message._id", " AND ", "file_hash = ?", A1112);
        A1112.append(" AND ");
        C17900vP.A0c("enc_file_hash = ?", " AND ", "message_type in ('3', '1' ) ", " ORDER BY sort_id DESC", A1112);
        A0G = AnonymousClass000.A0y(" LIMIT 10", A1112);
        StringBuilder A104 = AnonymousClass000.A10();
        C17900vP.A0c("SELECT ", str, " FROM ", "available_message_view", A104);
        A104.append(A0Y);
        A104.append("message_type  IN ('2', '1', '25', '3', '28', '13', '29')");
        A104.append(" AND ");
        C17890vO.A10(" ( NOT (message_type == 2 AND origin == 1)  OR (origin != 1))", " AND ", "chat_row_id = ?", A104);
        String obj = A104.toString();
        A0A = obj;
        A09 = C17900vP.A0A(obj, " ORDER BY sort_id DESC");
        StringBuilder A1113 = AnonymousClass000.A11("SELECT ");
        AnonymousClass1H2.A02("media_columns", A1113, strArr);
        A1113.append(" FROM ");
        A1113.append("message_media AS media_columns");
        A1113.append(" JOIN ");
        C17890vO.A17(A1113, "(SELECT media.file_hash, MIN(media.message_row_id) AS message_row_id FROM available_message_view AS message LEFT JOIN message_media AS media ON media.message_row_id = message._id WHERE message.chat_row_id = ? AND message.message_type=20 AND message.from_me = 0 AND message.sort_id >= ? GROUP BY media.file_hash ORDER BY COUNT(media.file_hash) DESC LIMIT ?) AS top_sticker_hash");
        A1113.append("media_columns.message_row_id");
        A1113.append(" = ");
        A0I = AnonymousClass000.A0y("top_sticker_hash.message_row_id", A1113);
        StringBuilder A1114 = AnonymousClass000.A11("SELECT ");
        C17900vP.A0c(AnonymousClass1H2.A01("media_columns", strArr), " FROM ", "message_media AS media_columns", " JOIN ", A1114);
        C17900vP.A0c("(SELECT media.file_hash, MIN(media.message_row_id) AS message_row_id FROM available_message_view AS message LEFT JOIN message_media AS media WHERE media.message_row_id = message._id AND message.chat_row_id = ? AND message.message_type=20 AND message.from_me = 0 AND message.sort_id >= ? GROUP BY media.file_hash ORDER BY COUNT(media.file_hash) DESC LIMIT ?) AS top_sticker_hash", A0Y, "media_columns.message_row_id", " = ", A1114);
        A0J = AnonymousClass000.A0y("top_sticker_hash.message_row_id", A1114);
    }
}
